### ISSUE TITLE
Not compatible with last version of Pillow

### ISSUE THREAD

**Issue by neiraRail** [patlevin/face-detection-tflite#11]
Although downgrading Pillow to version 9.0.0 worked for me. There could be cases where is not possible.

**Comment by JustinQE** [comment]
instead of downgrading you can also change the one place that the pillow upgrade breaks it

Image.LINEAR -> Image.BILINEAR

(noting this here for anyone who wanders in, since I think the repo is unmaintained)

**Comment by patlevin** [comment]
I'll test and make the necessary changes this weekend.

**Comment by hegdeadithyak** [comment]
Hey ,After the pillow 10.0.0 release the PIL.Image.LINEAR was depricated so I suggest you to use version before 10.0.0

Thanks,
Adithya Hegde Kota

**Comment by hegdeadithyak** [comment]
@neiraRail You cna mark this as Closed.

Thanks,
**Adithya Hegde Kota**
