### ISSUE TITLE
Dlib

### ISSUE THREAD

**Issue by jayp84847** [patlevin/face-detection-tflite#4]
Yet I am working on project with dlib 68 face landmarks. But its not enough stable for further use. 
Dlib face landmark: http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2

But in some research I found most of stable face detection is based on pytorch. Can we make ".dat" with it or any suggestions for ".dat" file build.

Stable pytorch 68 face landmarks : https://github.com/facebookresearch/supervision-by-registration

**Comment by patlevin** [comment]
I don't want to be rude, but Github isn't [StackOverflow](https://stackoverflow.com) and you shouldn't spam the same question in 17 repositories.

This project has nothing to do with Dlib and if you need a Dlib implementation of the "Supervision By Registration"-paper, you will have to implement the algorithm described in the paper and train the model using Dlib.

I haven't read the paper yet and I never used Dlib so I can't help with either of these steps.
