### ISSUE TITLE
ValueError: bbox must be normalized

### ISSUE THREAD

**Issue by robert-go** [patlevin/face-detection-tflite#5]
Thanks for your awesome library
I'm trying to recolor iris
But some image have error: `ValueError: bbox must be normalized`
Here is the google collab to reproduce: https://colab.research.google.com/drive/1UL7F1f-8fyKXBoUg2YcVjAFDN_dfIcIS?usp=sharing

**Comment by patlevin** [comment]
Thank you for reporting this issue.

The library was a bit too strict with its coordinate system. It didn't anticipate images where not all of the returned face landmarks are actually located within the image (e.g. zoomed-in faces).

This will be fixed in the next release.

**Comment by patlevin** [comment]
The new version with the bugfix is available on [PyPi](https://pypi.org/project/face-detection-tflite/0.4.0/).
Your Google collab example works without errors now after fixing the import error [here](https://colab.research.google.com/drive/1UL7F1f-8fyKXBoUg2YcVjAFDN_dfIcIS#scrollTo=5Msw7ZA4VSI-&line=3&uniqifier=1) to:
```python
from fdlite.examples.iris_recoloring import recolor_iris
```

Many thanks for providing an example for proper repro 👍

**Comment by robert-go** [comment]
@patlevin  thank you for a quick update
It's worked
Can you update the tutorial to fix import recolor_iris ?
https://github.com/patlevin/face-detection-tflite/blob/main/docs/tutorial.md#fun-with-iris-detection

**Comment by patlevin** [comment]
> Can you update the tutorial to fix import recolor_iris ?
> https://github.com/patlevin/face-detection-tflite/blob/main/docs/tutorial.md#fun-with-iris-detection

The updated tutorial was part of the latest release - check the link.

**Comment by robert-go** [comment]
I mean the import recolor_iris line.
It hasn't been updated yet
![Screen Shot 2021-07-16 at 16 31 26](https://user-images.githubusercontent.com/64536259/125926609-b161b7a6-80dc-47c9-b248-3152a143c1ce.png)

**Comment by patlevin** [comment]
Nice catch! 😄 It's fixed now.

**Comment by robert-go** [comment]
Thank you @patlevin 
We can close this issue
