### ISSUE TITLE
How to train your face detection model?

### ISSUE THREAD

**Issue by vonchenplus** [patlevin/face-detection-tflite#9]
Hello @patlevin 

Thank you very much for your great work, I found a face detection model you provided ([face_detection_back.tflite](https://github.com/patlevin/face-detection-tflite/blob/main/fdlite/data/face_detection_back.tflite)) is very small, I would like to ask how you trained this model? Based on what architecture or what paper?

**Comment by patlevin** [comment]
All models are part of Google's [MediaPipe](https://google.github.io/mediapipe/solutions/face_mesh.html).

The face detection models are different configurations of the architecture described by the authors [here](https://sites.google.com/view/perception-cv4arvr/facemesh). All models have been created, trained, and published by Google.

The [paper](https://arxiv.org/pdf/1907.06724.pdf) describes the training process they used.

HTH,
Patrick

**Comment by vonchenplus** [comment]
Ok thanks, 
I didn't find [face_detection_back.tflite](https://github.com/patlevin/face-detection-tflite/blob/main/fdlite/data/face_detection_back.tflite) in mediapipe, maybe they already removed the model. 
Then I haven't been able to find their training code and train data.

**Comment by patlevin** [comment]
It seems that quite a few models used here have been removed, e.g. [v0.8.7](https://github.com/google/mediapipe/tree/v0.8.7) removed the iris landmarks model.

The models used here can be found in version [0.8.1](https://github.com/google/mediapipe/tree/0.8.1/mediapipe/models).

> Then I haven't been able to find their training code and train data.

Unfortunately it is normal for training data and -code to not be available. [Papers With Code](https://paperswithcode.com) is a good resource for publications that come with a public implementation.

**Comment by vonchenplus** [comment]
Ok thanks.
